#!/bin/bash
  
python3 -m lss_mapper MakePixs   --raw_data=./lss_mapper_params/input_list_gama09h.txt   --clean_catalog=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/clean_catalog.fits   --flatmap_info=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/flatmap_info.fits   --config=./lss_mapper_params/config.yml

python3 -m lss_mapper MaskMapper   --clean_catalog=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/clean_catalog.fits --flatmap_info=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/flatmap_info.fits   --dust_map=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/dust_map.fits   --star_map=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/star_map.fits   --bo_mask=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/bo_mask.fits   --masked_fraction=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/masked_fraction.fits   --depth_map=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/depth_map.fits  --cut_catalog=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/cut_catalog.fits   --config=./lss_mapper_params/config.yml

python3 -m lss_mapper SystMapper   --frames_data=/global/cscratch1/sd/damonge/HSC_ceci/PDR1_WIDE_frames.fits   --flatmap_info=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/flatmap_info.fits   --ccdtemp_maps=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/ccdtemp_maps.fits   --airmass_maps=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/airmass_maps.fits   --exptime_maps=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/exptime_maps.fits   --skylevel_maps=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/skylevel_maps.fits   --sigma_sky_maps=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/sigma_sky_maps.fits   --seeing_maps=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/seeing_maps.fits   --ellipt_maps=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/ellipt_maps.fits   --nvisit_maps=/global/cscratch1/sd/anicola/DATA/DESC-HSC-3x2pt/HSC_ceci/WIDE_GAMA09H_sirius_i24p5_out/nvisit_maps.fits   --config=./lss_mapper_params/config.yml



